theme: minima
title: Place to discuss everything about GenAI & Payments, 
author:Bijen
description: This site provides a mechanism to evaluate different AI models, their efficieny and accuracy.
Thsi also discuss and weigh in the use of Agentic AI and workflows in solving different problem. 
Here we will talk about Flow Engineering  
